In [1]:
import torch

In [4]:
# 初期化されてないある次元のTensorを作成する
# (1次元の要素数, ２次元の要素数, .....)
x = torch.empty(5,3)
print(x)

tensor([[2.8026e-45, 4.5660e-41, 2.8026e-45],
        [2.1449e+20, 1.4013e-45, 0.0000e+00],
        [3.9236e-44, 0.0000e+00, 3.3570e+28],
        [4.5660e-41, 1.4013e-45, 4.5660e-41],
        [1.4013e-45, 1.9346e-19, 1.4013e-45]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.5456, 0.6568, 0.0102],
        [0.6545, 0.5081, 0.2129],
        [0.9283, 0.1992, 0.5302],
        [0.5121, 0.0334, 0.6027],
        [0.0755, 0.4262, 0.0842]])


In [7]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0419,  0.1357,  0.2533],
        [-1.8527,  0.6582,  1.0350],
        [ 0.7579,  0.7028, -0.7452],
        [ 0.6382,  0.4235, -1.3473],
        [-0.4702, -1.0031,  1.3611]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)

In [13]:
# Tensorの足し方は２通り
print(x+y)

tensor([[ 0.3296,  0.6842,  1.2496],
        [-1.8265,  0.7894,  1.8707],
        [ 1.2442,  1.5899, -0.5123],
        [ 0.7679,  0.6777, -0.9205],
        [-0.3414, -0.5488,  2.2513]])


In [14]:
print(torch.add(x, y))

tensor([[ 0.3296,  0.6842,  1.2496],
        [-1.8265,  0.7894,  1.8707],
        [ 1.2442,  1.5899, -0.5123],
        [ 0.7679,  0.6777, -0.9205],
        [-0.3414, -0.5488,  2.2513]])


In [17]:
# outで出力先のTensorを上書き
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3296,  0.6842,  1.2496],
        [-1.8265,  0.7894,  1.8707],
        [ 1.2442,  1.5899, -0.5123],
        [ 0.7679,  0.6777, -0.9205],
        [-0.3414, -0.5488,  2.2513]])


In [18]:
# add_で足した上で一方の変数に上書き
y.add_(x)
print(y)

tensor([[ 0.3296,  0.6842,  1.2496],
        [-1.8265,  0.7894,  1.8707],
        [ 1.2442,  1.5899, -0.5123],
        [ 0.7679,  0.6777, -0.9205],
        [-0.3414, -0.5488,  2.2513]])


In [19]:
# numpyのスライスは同様に使用可能 
print(x[:, 1])

tensor([ 0.1357,  0.6582,  0.7028,  0.4235, -1.0031])


In [29]:
# 4x4のtensor次元を作成
x = torch.randn(4, 4)

In [30]:
print(x)

tensor([[ 0.0872, -0.7700, -1.2317,  0.4599],
        [ 1.4660, -0.8161, -1.2043,  0.9040],
        [-0.0286, -1.1410, -0.1573,  0.4124],
        [ 0.1313,  1.6486, -0.0080, -0.5545]])


In [31]:
# view関数で次元数を変更
# １次元の配列に変更
# 要素数が足りないとエラーが出る(自動で補完をしてくれない)
y = x.view(16)
print(y, y.size())

tensor([ 0.0872, -0.7700, -1.2317,  0.4599,  1.4660, -0.8161, -1.2043,  0.9040,
        -0.0286, -1.1410, -0.1573,  0.4124,  0.1313,  1.6486, -0.0080, -0.5545]) torch.Size([16])


In [32]:
# -1で次元数を減らすことができる
# 一つ減るのではなく，(-1, x)のxの値に適した形に変換
z = x.view(-1, 8)
print(z, z.size())

tensor([[ 0.0872, -0.7700, -1.2317,  0.4599,  1.4660, -0.8161, -1.2043,  0.9040],
        [-0.0286, -1.1410, -0.1573,  0.4124,  0.1313,  1.6486, -0.0080, -0.5545]]) torch.Size([2, 8])


In [33]:
# item()によって通常の値として取得できる(intやdouble, float型？)
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3309])
0.33085983991622925


In [36]:
# TensorからNumPyへの変換
# メモリを共有するため，一方を変更するともう一方も変更される
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [40]:
# numpy から Tensorへの変換
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [41]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.3309], device='cuda:0')
tensor([1.3309], dtype=torch.float64)
